### ISSUE TITLE
Missing selected index

### ISSUE THREAD

**Issue by YSDC** [kmcgill88/McPicker-iOS#13]
Could be interesting to have the index of the selected item.

I've done it locally directly in the McPicker.swift file here:

```
    public func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        self.pickerSelection[component] = pickerData[component][row]
        self.pickerSelection[1] = String(row)
    }
```

I then get the result in the done Handler:

```
            mcPicker.show { (selections: [Int : String]) -> Void in
                self.mySelection = myArray[Int(selections[1]!)!]
            }
```

**Comment by kmcgill88** [comment]
McPicker isn't meant to give you an index, its meant to give you the selection result. Thats why the `doneHandler` gives you the selected string per component. 

One thing I didn't put in the README which I should perhaps clarify. McPicker takes an array of string arrays, `data: [[String]]`, as a parameter. So, if you passed
```
let passedInData: [[String]] = [
    ["Sir", "Mr", "Mrs", "Miss"], // Component 0
    ["Kevin", "Lauren", "Kibby", "Stella"] // Component 1
]
```
and during initialization McPicker by default sets `selections` to `[0 : "Sir", 1 : "Kevin"]` for initial values (aka, first item per component). When you select done the `doneHandler` passes back
```
mcPicker.show { selections in
        if let prefix = selections[0], let name = selections[1] {
            self.label.text = "\(prefix) \(name)"
        }
}
```
The label would then read `Sir Kevin` and from my perspective there is no need to reference back to `passedInData` as you do in your example with `myArray`. 


If you really do want to know the index I'd suggest doing something like this
```
// Say you passed this
let passedInData: [[String]] = [
    ["Sir", "Mr", "Mrs", "Miss"], // Will be component 0
    ["Kevin", "Lauren", "Kibby", "Stella"] // Component 1
]

// Imagine a user selected these
let selections: [Int:String] = [0 : "Sir", 1 : "Stella"]

// Inside the doneHandler do
if let secondComponentSelection = selections[1] {
    print(passedInData[1].index(of: secondComponentSelection)!)
    // Prints 3
}  else {
    print("Component selection doesn't exists")
}

// repeat per selection
```

Hopefully this helps. If not, feel free to make a PR and we can have a look at what you have in mind.

**Comment by isaranjha** [comment]
The provided solution doesn't work if there are repeats in the data array. For example, if you display a McPicker for selected user named folders, there is no guarantee that the user has named each folder uniquely. Returning the index of the selected item and then cross referencing that to the data source used when setting up the McPicker is the superior and only safe way to accomplish this. What do you think?
