### ISSUE TITLE
Custom ToolbarItems

### ISSUE THREAD

**Issue by Mahan3340** [kmcgill88/McPicker-iOS#16]
Hi , please provide some method to change default ToolbarItems text (done,cancel) and setToolBarItems method that gets and array of buttons is not working properly in viewing them have you checked them ? 
how to add two custom toolbarItems like "done" and "cancel" but with custom styles ?

**Comment by kmcgill88** [comment]
Hey @mahan3340 thanks for letting me know. I'll have a look when I get some free time. I'll probably implement something similar to what I did for a [KMKeys](https://github.com/kmcgill88/KMKeys-iOS/blob/master/KMKeys/Classes/KMKeyBarButtonItem.swift)

**Comment by kmcgill88** [comment]
@Mahan3340 check out version 0.5.0, should be what you need.
