### ISSUE TITLE
Support for swift 4

### ISSUE THREAD

**Issue by jethmalani** [kmcgill88/McPicker-iOS#18]
Does this project support swift 4?

**Comment by kmcgill88** [comment]
Hi @jethmalani. I haven't tried it yet but fully intend to have McPicker be fully Swift 4 compatible. I'll try it out soon!

**Comment by jethmalani** [comment]
Awesome! Thanks a lot. I am seeing a few issues since it is not in swift 4.

**Comment by kmcgill88** [comment]
Shoot, but good to know. Can you post what issue(s) you are seeing?

**Comment by jethmalani** [comment]
So when we are displaying data, we are not able to select anything. Here is the code we are using and when something is selected, nothing prints. 

`let mcPicker = McPicker(data: [dataToDisplay])
        mcPicker.toolbarButtonsColor = UIColor( red: 224/255, green: 160/255, blue:12/255, alpha: 1.0)
        mcPicker.show { (selection) in
            print ("selections are \(selection)")
        }`

**Comment by jethmalani** [comment]
Did you get a chance to look into this? This is one of the last major issues we are seeing in our project. Do you know when you will get a chance to look into it? Really like to project by the way!

**Comment by kmcgill88** [comment]
Sorry no I haven't gotten to it. It will probably next week. 

What does `dataToDisplay` look like? Just want to make sure its an array of string arrays. 
```[['component 1 things'], ['component 2 things']]```

**Comment by thephucit** [comment]
Xcode 9, swift 4 same issue, here is my code, it's just show picker but not receive selections
`picker.show { selections in
            if let selected = selections[0] {
                print(selected)
            }
        }`

**Comment by kmcgill88** [comment]
Thanks for the report @thephucit. Is there any error message or does Swift 4 just not pass back the selections?

**Comment by thephucit** [comment]
@kmcgill88  have no any happend when I selected

**Comment by jethmalani** [comment]
No error message. It just doesn't pass back any selections. It just dismisses the picker view.

**Comment by thephucit** [comment]
actualy, this problem not depend to swift 4, I try on IOS 10.3.3 or low than it's working well, 
but on IOS 11 >> No error message. It just doesn't pass back any selections. It just dismisses the picker view.

**Comment by kmcgill88** [comment]
Been digging into this. For some reason in Swift 4 the `cancel` method is always called for some reason, thus never passing back `selections`. Still debugging.

**Comment by kmcgill88** [comment]
I threw a questions on [stackoverflow](https://stackoverflow.com/questions/46516238/swift-4-consistently-calls-wrong-selector).

**Comment by kmcgill88** [comment]
I found the issue and working on the fix now. Should be done in a few!

**Comment by kmcgill88** [comment]
This has been resolved with version [0.5.1](https://github.com/kmcgill88/McPicker-iOS/releases/tag/0.5.1), enjoy!
