### ISSUE TITLE
The cancel handler is called even though the user is clicking on the done button.

### ISSUE THREAD

**Issue by sundeepdev** [kmcgill88/McPicker-iOS#20]
`self.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(cancel)))`
The above line in the McPicker.setup() method is causing this issue.

**Comment by kmcgill88** [comment]
What version of mcpicker are you using?

**Comment by kmcgill88** [comment]
This was an issue in 0.5.0 + swift 4. 0.5.1 corrected it. Please let me know if you are seeing different behavior.

**Comment by sundeepdev** [comment]
Yup just noticed that you've a new version on cocoa-pod when I tried to fix the issue on the example project. So you can close it. Thanks for the quick response.

**Comment by sundeepdev** [comment]
I had version 0.5.0. I'm closing the issue.

**Comment by kmcgill88** [comment]
You made me nervous for a minute haha! Glad it was an easy fix. Enjoy!
