### ISSUE TITLE
toolbarItemsFont toolbarButtonsColor not working 

### ISSUE THREAD

**Issue by Mahan3340** [kmcgill88/McPicker-iOS#21]
Hi , `mcPicker.toolbarItemsFont = UIFont(name: "W_koodak", size: 17)!`  this line is not working if its called before setting the toolbarItems and if its called after setting them its working fine and also its true for toolbarButtonsColor and maybe some more

**Comment by kmcgill88** [comment]
Thanks for letting me know. I figured this could be an issue. Since it works if you do the ordering right this isn’t a high priority right now. I’ll have a look next time I’m in the code.

**Comment by Mahan3340** [comment]
yea sure its not important that much but wanted to mention that 👍

**Comment by kmcgill88** [comment]
Absolutely, thanks for the post!

**Comment by kmcgill88** [comment]
Corrected in PR #33. Thanks! 🥇
