### ISSUE TITLE
Is there a way to use McPicker with a TextField as InputView ?

### ISSUE THREAD

**Issue by sundeepdev** [kmcgill88/McPicker-iOS#22]
I want to use McPicker as an InputViews on my textfield. I don't have access to the PickerView

**Comment by kmcgill88** [comment]
I am not following. Can you please elaborate your question with an example use case? Thanks!

**Comment by sundeepdev** [comment]
Sorry for the short description. Let me elaborate. So if you want to use a picker when a user tries to enter some data in textfield. You can set the UIPickerView as the inputview for the UITextField.

`firstNameTextField.inputView = uiPickerView`

What it does is that it shows the PickerView instead of the Keyboard when a user begins editing. So the question is, if there's a way to do that using McPicker? The benefit is that it handles the showing and hiding of the pickerView using the normal textfield delegates.

**Comment by kmcgill88** [comment]
Oh! I gotcha! Currently no, there is no access to the underlying UIPickerView so you wouldn't be able to do this. I haven't considered the use case but I think its a great one. Do you have any suggestions how to wire it up? Maybe add something like `showAsInputView`?

**Comment by kmcgill88** [comment]
@sundeepdev I've added a solution in #34
