### ISSUE TITLE
Pod Update to version 0.5.1 Error on setTitleTextAttributes[.font

### ISSUE THREAD

**Issue by fabriciomasiero** [kmcgill88/McPicker-iOS#23]
Hi, I updated the pod because I had issue #20 . But after updating and building my project, a compilation error occurred, is it normal? thank you

![captura de tela 2017-10-11 as 17 14 40](https://user-images.githubusercontent.com/2105842/31464423-fb122056-aea7-11e7-8eb4-e771f21f2559.png)

**Comment by kmcgill88** [comment]
Hmm, when I published it was fine for me. What version of swift are you using? I was using 4.

**Comment by fabriciomasiero** [comment]
My project are using Swift 4, but i dont updated the swift syntax in my pods project. 

Summing up: My project = swift 4
                       Pods project = swift 3.1

**Comment by kmcgill88** [comment]
I did update the pod for swift 4. I ~think~ you must tell Xcode McPicker uses swift 4 and you can leave the rest as 3.

**Comment by kmcgill88** [comment]
Just tested this out and confirm my suspicion. McPicker needs to compile with Swift 4 and you must have it set to compile with Swift 3. Just change the toggle in your project and it should be good to go! A picture is worth 💯 words.

![swift4](https://user-images.githubusercontent.com/1992370/31473353-8515800c-aeb9-11e7-9460-946350b552b2.png)

I will update the README to outline this. Thanks for reporting! 🥇  Please let me know if this does the trick for ya.

**Comment by fabriciomasiero** [comment]
Thanks @kmcgill88 works fine!!!! Thank you very much!!

**Comment by fabriciomasiero** [comment]
WORKS !!!! Thanks you very much @kmcgill88
