### ISSUE TITLE
ToolbarItems Font For Other States

### ISSUE THREAD

**Issue by Mahan3340** [kmcgill88/McPicker-iOS#24]
Hi , setting ToolbarItems Fonts is currently just set for the .normal state of the buttons and when you click it or longPress (hold) on it the font is changed to default for a moment or for the time you are holding it

**Comment by kmcgill88** [comment]
Hi @Mahan3340, thanks for the post. Do you have any suggestions to improve this? `.normal` is currently [hardcoded](https://github.com/kmcgill88/McPicker-iOS/blob/master/McPicker/Classes/McPicker.swift#L70).

**Comment by Mahan3340** [comment]
Hi , sorry I forgot to mention that I fixed it by adding `.selected` state like below
 `barButtonItem.setTitleTextAttributes([.font: toolbarItemsFont!], for:UIControlState.selected)`

**Comment by kmcgill88** [comment]
I assume you did that in your own fork? This seems like a nice option to add in to McPicker but I can’t think of a way to do it using the ‘didSet’ approach. I think it would have to be changed to a ‘func’. What do you think?

**Comment by Mahan3340** [comment]
yea I unlocked the files and made changes to them , and I've also added this to didSet  

```
 public var toolbarItemsFont: UIFont? {
        didSet {
            applyToolbarButtonItemsSettings { (barButtonItem) in
                barButtonItem.setTitleTextAttributes([.font: toolbarItemsFont!], for: .normal)
                 barButtonItem.setTitleTextAttributes([.font: toolbarItemsFont!], for:UIControlState.selected)
               }
        }
    }

```

**Comment by kmcgill88** [comment]
Actually, looking at the code you posted I feel like setting the same font for `.normal` and `.selected` should be the default behavior. I'd sure think 99% of the time you'd want these the same. I will get it added the next time I work on this.

**Comment by Mahan3340** [comment]
yea I guess no one want different fonts for these states so can be added right there 👍
