### ISSUE TITLE
Picker Selection not working in iOS 11.0.3

### ISSUE THREAD

**Issue by datamaru** [kmcgill88/McPicker-iOS#26]
Breakpoint inside the doneHandler is not called when I press done. It's still working in iOS 10.

**Comment by kmcgill88** [comment]
Be sure to use `0.5.2` and that McPicker is using [Swift 4](https://github.com/kmcgill88/McPicker-iOS/issues/23). 

If you are still having issues let me know.

**Comment by datamaru** [comment]
Updated the pod and works well. Sorry for the false alarm.
