### ISSUE TITLE
it's too slow...

### ISSUE THREAD

**Issue by greatsk55** [kmcgill88/McPicker-iOS#27]
Complete photo selection
 It is too slow to return to the view I called.

I do not know if it's just me or the problem with the simulator.

**Comment by kmcgill88** [comment]
Hmm, did you actidentially toggle on the simulators [slowed animations](https://stackoverflow.com/questions/8624519/simulator-slow-motion-animations-are-now-on)?

**Comment by azhararmar** [comment]
I am using it in my project, after testing it in various devices, It works perfect for me.

**Comment by kmcgill88** [comment]
Thanks for the feedback @azhararmar. Closing issue.
