### ISSUE TITLE
Is there any way using like 'didselect'??

### ISSUE THREAD

**Issue by LeeGwangYong** [kmcgill88/McPicker-iOS#30]
#I have two related picker view
first picker : [ [Alphabet, Numbers] ]
second picker : [ [a,b,c, ...] or [1,2,3, ...] ]
if I select 'Alphabet' at first picker, second picker show [a,b,c, ...]
and if select 'Numbers', show [1,2,3, ...]

**Comment by kmcgill88** [comment]
Hi @LeeGwangYong,

Were you trying to do this with 1 instance of McPicker? My first instinct says show McPicker with `[ [Alphabet, Numbers] ]`, when the user makes a selection and McPicker closes, use the selection to show another instance of McPicker with `[ [a,b,c, ...] or [1,2,3, ...] ]` then once the user makes a selection you will have your final selections.

Adding a delegate to just listen for `didSelect` isn't bad ideal though! We could [add a delegate callback here](https://github.com/kmcgill88/McPicker-iOS/blob/master/McPicker/Classes/McPicker.swift#L402).

**Comment by LeeGwangYong** [comment]
Yes! I want to use just 1 instance of McPicker. Thank you for your quick response.
And I will try to follow your advice. 
Thank you 👍

**Comment by kmcgill88** [comment]
You could also try to subclass McPicker and override the delegate methods. Not sure that'll work but worth a shot. I'd like to keep McPicker simple and easy to use so I sorta shy away from adding things on the limb.

**Comment by LeeGwangYong** [comment]
I added some code at `didselect` method 

```swift
public func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        self.pickerSelection[component] = pickerData[component][row]
        (... update pickerData[1]...)
		picker.reloadComponent(1)
        picker.selectRow(0, inComponent: 1, animated: true)
        pickerSelection[1] = pickerData[1][0]
    }
```
it's really cool library

**Comment by kmcgill88** [comment]
Thanks @LeeGwangYong! [This is a similar request](https://github.com/kmcgill88/McPicker-iOS/pull/29) @AlaeddineOuerteni pointed out wanting some control over the delegate too. I'm open to the idea, just curious how to best implement it. My first thought is to have McPicker have its own delegate method(s). Like `McPickerViewDelegate`, which would enforce proper use of `data: [[String]]` and `pickerSelection: [Int:String]` without actually exposing either `public`ly. I'm afraid it's opened it could be easily misused.

**Comment by kmcgill88** [comment]
Hello @LeeGwangYong, I have not cut a release yet but you might be interested in #32. It adds a `SelectionChangedHandler`. See the updated REAME in master branch for an example. I will cut a `1.0.0` release very soon! 💯
