### ISSUE TITLE
Default selected option

### ISSUE THREAD

**Issue by UtkuDalmaz** [kmcgill88/McPicker-iOS#35]
How can I set a default text for UIView as McTextField?

**Comment by kmcgill88** [comment]
A `McTextField` is a  [UITextField](https://github.com/kmcgill88/McPicker-iOS/blob/master/McPicker/Classes/McTextField.swift#L23) not a `UIView`. You can drag out a `UITextField` in Interface Builder then change its class to `McTextField`. In code the [example app shows how to use it](https://github.com/kmcgill88/McPicker-iOS/blob/master/Example/McPicker/ViewController.swift#L34-L54). Setting a default text is as simple as `mcTextField?.text = "My Text."`. 

Hope that helps!
