### ISSUE TITLE
Is there a way to set Picker to select a particular text

### ISSUE THREAD

**Issue by Pod5GS** [kmcgill88/McPicker-iOS#36]
I'm trying to custom the cancel logic. Instead of displaying 'Canceled', I want the inputview display the text user selects last time, and set Picker to select the text user selects last time.

**Comment by kmcgill88** [comment]
Hey @Pod5GS, yes you can do that. You will need to create some `McPickerBarButtonItem`'s. Then `setToolbarItems`. The `.done` is the right side and will fire the closures with results and the `.cancel` does just that, and will not fire the closures you pass to `McPicker`.

```swift
let fixedSpace = McPickerBarButtonItem.fixedSpace(width: 20.0)
let flexibleSpace = McPickerBarButtonItem.flexibleSpace()
let fireButton = McPickerBarButtonItem.done(mcPicker: mcPicker, title: "Fire!!!") // Set custom Text
let cancelButton = McPickerBarButtonItem.cancel(mcPicker: mcPicker, title: "The Cancel Text You Want") 

mcPicker.setToolbarItems(items: [fixedSpace, cancelButton, flexibleSpace, fireButton, fixedSpace])
```

Good luck!
