### ISSUE TITLE
how can i set donebutton uifont ?

### ISSUE THREAD

**Issue by c941010623** [kmcgill88/McPicker-iOS#39]
I want only done button set font and bold
how can I set?

**Comment by kmcgill88** [comment]
Hi @c941010623,

`mcPicker.toolbarItemsFont = UIFont(name:"American Typewriter", size: 17)!` allows you to set both. If you want to set just one of them you could use the [customized](https://github.com/kmcgill88/McPicker-iOS/blob/master/Example/McPicker/ViewController.swift#L101) McPicker approach and just add

```swift
doneButtonItem.setTitleTextAttributes([.font: toolbarItemsFont!], for: .normal)
doneButtonItem.setTitleTextAttributes([.font: toolbarItemsFont!], for: .selected)
```

That should just set the one you want.

**Comment by c941010623** [comment]
thank you ^^
