### ISSUE TITLE
return row position uipickerview

### ISSUE THREAD

**Issue by javmorales** [kmcgill88/McPicker-iOS#41]
how I can know that the position uipickerview is selected?

**Comment by kmcgill88** [comment]
@javmorales you can use the [selectionChangedHandler](https://github.com/kmcgill88/McPicker-iOS/blob/master/Example/McPicker/ViewController.swift#L80) to determine what is selected before `doneHandler` or `cancelHandler ` are called.

**Comment by kmcgill88** [comment]
No response, closing.
