### ISSUE TITLE
Spacing between components

### ISSUE THREAD

**Issue by clapslock** [kmcgill88/McPicker-iOS#42]
Is it possible to change the default spacing between different components (just like the spacing between buttons in the toolbar)?

**Comment by kmcgill88** [comment]
Hey @clapslock, good question. I don't know off the top of my head. If you figure out a way please let me know. PR's are welcome too. 😄

**Comment by kmcgill88** [comment]
@clapslock did you figure anything out about this? Now that I've read this again I bet you could [setToolbarItems](https://github.com/kmcgill88/McPicker-iOS/blob/master/Example/McPicker/ViewController.swift#L103) and set whatever fixed spaces you wanted.

**Comment by clapslock** [comment]
So, it turned out that the feature I needed the McPicker for will not be available in my app's version 1.0. 
At the moment I'm waiting for the API for the said tool. I'll give it another try as soon as it's ready and I'll let you know!
