### ISSUE TITLE
Problem with swift 4.2

### ISSUE THREAD

**Issue by boardmain** [kmcgill88/McPicker-iOS#43]
Unable to build with swift 4.2 and xcode 10.0

**Comment by kmcgill88** [comment]
Thanks for the heads up. I don’t have Xcode 10 yet. I will have a look when Mojave comes out.

**Comment by iCodeTechnologies** [comment]
It must be something to do with Swift 4.2 because I can compile it with XCode 10.0 but I haven't updated the app to Swift 4.2 yet.

**Comment by kmcgill88** [comment]
Is it possible that https://github.com/kmcgill88/McPicker-iOS/issues/37 would make this pod compile with Swift 4.1 even if your main project is 4.2? My understanding is each pod tries to compile to whatever the main project is set as. Adding the option to the podfile would make the pod a little smarter to choose the swift version for itself. In this case when people have already bumped to 4.2 this pod would still compile with 4.1 and things would keep working.

I'm not against merging #44 and upgrading it to 4.2 but doing so will force everyone using the pod to upgrade. I like the idea of being flexible for people. Maybe this can be upgrade to 4.2 and add the swift version in the podfile for the future.

**Comment by jadsalhani** [comment]
I believe the Podspec already does that, as discussed [here](https://github.com/CocoaPods/CocoaPods/issues/7327#issuecomment-360621040). So if the version isn't specified in the spec, it compiles to the project Swift version set by the user. 

Leaves us with the choice; do we make the upcoming change backwards compatible or leave them version-separated? Considering all the upgrades with Swift 4.2, it's worth releasing a new explicit version for Swift 4.2 support that isn't backwards compatible
