### ISSUE TITLE
Is there a way to get the selected row or index, besides the text

### ISSUE THREAD

**Issue by jcifuentes91** [kmcgill88/McPicker-iOS#52]
I was trying to use this to choose from a list of [id:String], but since it only accepts [[String]], I created two lists one of [id] and one of [[String]], I want to know if I can get the selected row (index) in order to get the id from the other list, thanks. 
Note: I have repeating strings so IndexOf will not help

**Comment by ewan34500** [comment]
Please can you give the solution ?
