### ISSUE TITLE
Why was tap on Popup View removed? Is there a way to add it back?

### ISSUE THREAD

**Issue by cachobong** [kmcgill88/McPicker-iOS#58]

**Comment by kmcgill88** [comment]
I wasn't aware this was removed?

**Comment by cachobong** [comment]
I updated the Pod and it wasn't functioning anymore so I did a code compare and the tap gesture was removed.

**Comment by cachobong** [comment]
@kmcgill88 seems that it was added by the previous developer and they committed the Pods folder. Sorry about the hassle.
