### ISSUE TITLE
Xcode 12 build errors

### ISSUE THREAD

**Issue by warpling** [kmcgill88/McPicker-iOS#66]
Since updating and attempting to compile with Xcode 12 beta I've getting build errors from McPicker for these two functions
`public class func flexibleSpace() -> McPickerBarButtonItem`
`public class func fixedSpace(width: CGFloat) -> McPickerBarButtonItem`

**Comment by warpling** [comment]
If anyone needs a branch that fixes this in the time being: https://github.com/warpling/McPicker-iOS

**Comment by cerupcat** [comment]
@warpling, with your version I'm getting `Cannot override a Self return type with a non-Self` return type with Xcode 12 Beta 4.

Looks like it needs to return `Self` and not `McPickerBarButtonItem`

**Comment by warpling** [comment]
Huh, strange. I didn't have to change that to be able to compile with Swift 5 in Xcode 12 (not sure which beta).

**Comment by lukemmtt** [comment]
I haven't done extensive testing, but I saw this same issue today and it seems to be the result of Xcode 12 switching my app's Swift version from 4.2 to 5. I had a compile-time error about the override keyword, and I changed the Swift level in Build settings back to 4.2 (as it is in my production Xcode 11.6), and the app built without a problem.

**Comment by UtkuDalmaz** [comment]
How to fix this man? Cannot override a Self return type with a non-Self

**Comment by warpling** [comment]
@UtkuDalmaz not sure. I just accepted the changes Xcode suggested and it compiled for me.

**Comment by cerupcat** [comment]
It may also depend on what you're using.

For me, with SPM and XcodeBeta 4/5, I needed to change 2 files that it was complaining about. The changes made though are different than in @warpling branch. If I get a chance, I'll make a branch.

**Comment by kmcgill88** [comment]
Started on a fix for this. Checkout https://github.com/kmcgill88/McPicker-iOS/pull/69 comments more than welcome!

**Comment by kmcgill88** [comment]
`3.0.0` has been published and requires xcode 12.
